
export const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  VALIDATION: 422,
  INTERNAL_SERVER_ERROR: 500,
};


export const COMMON_ERROR_MESSAGE = {
  RESOURCE_NOT_FOUND: "Resource not found",
  BAD_REQUEST: "Bad Request",
  UNAUTHORIZATION: "Unauthorization",
  FORBIDDEN: "Forbidden",
  INTERNALSERVER: "InternalServer",
  CONFLICT: "Hotel already exists within the tenant",
  VALIDATION: "Validation error",
};


export const CODES = {
  RESOURCE_NOT_FOUND: "NOT_FOUND",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNALSERVER: "INTERNAL_SERVER_ERROR",
  CONFLICT: "CONFLICT",
  VALIDATION: "VALIDATION_ERROR"
};